<form > 
<div class="qualquercoisa">
          
    <p> &emsp; Em um sentido amplo, um contrato é uma operação econômica entre duas ou mais pessoas.[1][2] Nesse sentido, um contrato é uma troca econômica, visando a circulação de riqueza, sendo sinônimo do conceito de negócio.[3] Sob o ponto de vista do direito, um contrato é a formalização jurídica de uma operação econômica,[4] formalização essa entendida como um instrumento jurídico que vincula os contratantes aos compromissos por eles assumidos.[5] Assim, celebrado um contrato, as partes ficam obrigadas aos seus termos, sob pena de uma sanção legal no caso de descumprimento. Desse modo, pode-se definir um contrato como um acordo de vontades legalmente exequível.[2] A figura jurídica do contrato apresenta-se como uma forma de o legislador regular trocas econômicas e orientá-las segundo critérios políticos.[6] Daí porque cada sistema jurídico apresenta regras distintas sobre contratos, bem como cada sistema econômico também irá apresentar diferentes matizes sobre o direito contratual.[7]
          Em um sentido amplo, um contrato é uma operação econômica entre duas ou mais pessoas.[1][2] Nesse sentido, um contrato é uma troca econômica, visando a circulação de riqueza, sendo sinônimo do conceito de negócio.[3] Sob o ponto de vista do direito, um contrato é a formalização jurídica de uma operação econômica,[4] formalização essa entendida como um instrumento jurídico que vincula os contratantes aos compromissos por eles assumidos.[5] Assim, celebrado um contrato, as partes ficam obrigadas aos seus termos, sob pena de uma sanção legal no caso de descumprimento. Desse modo, pode-se definir um contrato como um acordo de vontades legalmente exequível.[2] A figura jurídica do contrato apresenta-se como uma forma de o legislador regular trocas econômicas e orientá-las segundo critérios políticos.[6] Daí porque cada sistema jurídico apresenta regras distintas sobre contratos, bem como cada sistema econômico também irá apresentar diferentes matizes sobre o direito contratual.[7]
          Em um sentido amplo, um contrato é uma operação econômica entre duas ou mais pessoas.[1][2] Nesse sentido, um contrato é uma troca econômica, visando a circulação de riqueza, sendo sinônimo do conceito de negócio.[3] Sob o ponto de vista do direito, um contrato é a formalização jurídica de uma operação econômica,[4] formalização essa entendida como um instrumento jurídico que vincula os contratantes aos compromissos por eles assumidos.[5] Assim, celebrado um contrato, as partes ficam obrigadas aos seus termos, sob pena de uma sanção legal no caso de descumprimento. Desse modo, pode-se definir um contrato como um acordo de vontades legalmente exequível.[2] A figura jurídica do contrato apresenta-se como uma forma de o legislador regular trocas econômicas e orientá-las segundo critérios políticos.[6] Daí porque cada sistema jurídico apresenta regras distintas sobre contratos, bem como cada sistema econômico também irá apresentar diferentes matizes sobre o direito contratual.[7]
      
      Em uma visão clássica sobre os contratos, influenciada pela ideologia liberal, a figura jurídica do contrato têm como função impor regras de bom funcionamento do mercado, evitando assim que as trocas comerciais sejam inteiramente expostas a acontecimentos imprevisíveis ou ao mero árbitro das partes.[8] A função do direito contratual, portanto, é criar deveres para as partes de modo a limitar seu comportamento, coibindo um conjunto de atitudes prejudiciais ao mercado. Para essa visão, o direito deve se limitar a criar meios para garantir a exequibilidade do contrato, pouco importando o seu conteúdo.[9] Mais recentemente, com o retrocesso do liberalismo clássico, a doutrina passou a discutir outras finalidades contratuais, mais voltadas à coletividade, como a função social do contrato.
      
      O direito vê o contrato como um negócio jurídico, o que significa que esse acordo deve obedecer certos requisitos legais para que se forme, seja considerado válido e produza efeitos. Não há uma uniformidade na matéria, com cada legislação apresentando seus próprios requisitos formais. Há uma forte tendência entre os juristas de considerar como contrato jurídico apenas os acordos de vontade que tenham um conteúdo patrimonial. Há, contudo, aqueles que entendem que todo acordo de vontades protegido pela lei será um contrato, importando dizer que figuras de valor afetivo e não patrimonial, como o casamento e o divórcio, serão considerados como contratos. Discute-se também se só seriam contratos aqueles celebrados por duas pessoas físicas ou pessoas jurídicas de de direito privado, ou se os acordos celebrados por pessoas jurídicas de direito público - comumente chamados de contratos administrativos - também se encaixariam na categoria.
      
      Contratos que não obedecem as formalidades legais serão reputados como inexistentes ou inválidos, a depender do vício no caso concreto. Sendo inexistentes ou inválidos, serão ineficazes, não produzindo efeitos. O contrato válido e eficaz, por outro lado, é juridicamente exequível, o que signifca que seu descumprimento poderá ser levado ao Poder Judiciário, por meio de uma ação judicial, que poderá resultar na imposição de um fazer ou não fazer a um dos contratantes, ou o pagamento de uma indenização pelo descumprimento contratual.[10]
      Em uma visão clássica sobre os contratos, influenciada pela ideologia liberal, a figura jurídica do contrato têm como função impor regras de bom funcionamento do mercado, evitando assim que as trocas comerciais sejam inteiramente expostas a acontecimentos imprevisíveis ou ao mero árbitro das partes.[8] A função do direito contratual, portanto, é criar deveres para as partes de modo a limitar seu comportamento, coibindo um conjunto de atitudes prejudiciais ao mercado. Para essa visão, o direito deve se limitar a criar meios para garantir a exequibilidade do contrato, pouco importando o seu conteúdo.[9] Mais recentemente, com o retrocesso do liberalismo clássico, a doutrina passou a discutir outras finalidades contratuais, mais voltadas à coletividade, como a função social do contrato.
      
      O direito vê o contrato como um negócio jurídico, o que significa que esse acordo deve obedecer certos requisitos legais para que se forme, seja considerado válido e produza efeitos. Não há uma uniformidade na matéria, com cada legislação apresentando seus próprios requisitos formais. Há uma forte tendência entre os juristas de considerar como contrato jurídico apenas os acordos de vontade que tenham um conteúdo patrimonial. Há, contudo, aqueles que entendem que todo acordo de vontades protegido pela lei será um contrato, importando dizer que figuras de valor afetivo e não patrimonial, como o casamento e o divórcio, serão considerados como contratos. Discute-se também se só seriam contratos aqueles celebrados por duas pessoas físicas ou pessoas jurídicas de de direito privado, ou se os acordos celebrados por pessoas jurídicas de direito público - comumente chamados de contratos administrativos - também se encaixariam na categoria.
      
      Contratos que não obedecem as formalidades legais serão reputados como inexistentes ou inválidos, a depender do vício no caso concreto. Sendo inexistentes ou inválidos, serão ineficazes, não produzindo efeitos. O contrato válido e eficaz, por outro lado, é juridicamente exequível, o que signifca que seu descumprimento poderá ser levado ao Poder Judiciário, por meio de uma ação judicial, que poderá resultar na imposição de um fazer ou não fazer a um dos contratantes, ou o pagamento de uma indenização pelo descumprimento contratual.[10]
      Em uma visão clássica sobre os contratos, influenciada pela ideologia liberal, a figura jurídica do contrato têm como função impor regras de bom funcionamento do mercado, evitando assim que as trocas comerciais sejam inteiramente expostas a acontecimentos imprevisíveis ou ao mero árbitro das partes.[8] A função do direito contratual, portanto, é criar deveres para as partes de modo a limitar seu comportamento, coibindo um conjunto de atitudes prejudiciais ao mercado. Para essa visão, o direito deve se limitar a criar meios para garantir a exequibilidade do contrato, pouco importando o seu conteúdo.[9] Mais recentemente, com o retrocesso do liberalismo clássico, a doutrina passou a discutir outras finalidades contratuais, mais voltadas à coletividade, como a função social do contrato.
      
      O direito vê o contrato como um negócio jurídico, o que significa que esse acordo deve obedecer certos requisitos legais para que se forme, seja considerado válido e produza efeitos. Não há uma uniformidade na matéria, com cada legislação apresentando seus próprios requisitos formais. Há uma forte tendência entre os juristas de considerar como contrato jurídico apenas os acordos de vontade que tenham um conteúdo patrimonial. Há, contudo, aqueles que entendem que todo acordo de vontades protegido pela lei será um contrato, importando dizer que figuras de valor afetivo e não patrimonial, como o casamento e o divórcio, serão considerados como contratos. Discute-se também se só seriam contratos aqueles celebrados por duas pessoas físicas ou pessoas jurídicas de de direito privado, ou se os acordos celebrados por pessoas jurídicas de direito público - comumente chamados de contratos administrativos - também se encaixariam na categoria.
      
      Contratos que não obedecem as formalidades legais serão reputados como inexistentes ou inválidos, a depender do vício no caso concreto. Sendo inexistentes ou inválidos, serão ineficazes, não produzindo efeitos. O contrato válido e eficaz, por outro lado, é juridicamente exequível, o que signifca que seu descumprimento poderá ser levado ao Poder Judiciário, por meio de uma ação judicial, que poderá resultar na imposição de um fazer ou não fazer a um dos contratantes, ou o pagamento de uma indenização pelo descumprimento contratual.[10]
          Em um sentido amplo, um contrato é uma operação econômica entre duas ou mais pessoas.[1][2] Nesse sentido, um contrato é uma troca econômica, visando a circulação de riqueza, sendo sinônimo do conceito de negócio.[3] Sob o ponto de vista do direito, um contrato é a formalização jurídica de uma operação econômica,[4] formalização essa entendida como um instrumento jurídico que vincula os contratantes aos compromissos por eles assumidos.[5] Assim, celebrado um contrato, as partes ficam obrigadas aos seus termos, sob pena de uma sanção legal no caso de descumprimento. Desse modo, pode-se definir um contrato como um acordo de vontades legalmente exequível.[2] A figura jurídica do contrato apresenta-se como uma forma de o legislador regular trocas econômicas e orientá-las segundo critérios políticos.[6] Daí porque cada sistema jurídico apresenta regras distintas sobre contratos, bem como cada sistema econômico também irá apresentar diferentes matizes sobre o direito contratual.[7]
      
      Em uma visão clássica sobre os contratos, influenciada pela ideologia liberal, a figura jurídica do contrato têm como função impor regras de bom funcionamento do mercado, evitando assim que as trocas comerciais sejam inteiramente expostas a acontecimentos imprevisíveis ou ao mero árbitro das partes.[8] A função do direito contratual, portanto, é criar deveres para as partes de modo a limitar seu comportamento, coibindo um conjunto de atitudes prejudiciais ao mercado. Para essa visão, o direito deve se limitar a criar meios para garantir a exequibilidade do contrato, pouco importando o seu conteúdo.[9] Mais recentemente, com o retrocesso do liberalismo clássico, a doutrina passou a discutir outras finalidades contratuais, mais voltadas à coletividade, como a função social do contrato.
      
      O direito vê o contrato como um negócio jurídico, o que significa que esse acordo deve obedecer certos requisitos legais para que se forme, seja considerado válido e produza efeitos. Não há uma uniformidade na matéria, com cada legislação apresentando seus próprios requisitos formais. Há uma forte tendência entre os juristas de considerar como contrato jurídico apenas os acordos de vontade que tenham um conteúdo patrimonial. Há, contudo, aqueles que entendem que todo acordo de vontades protegido pela lei será um contrato, importando dizer que figuras de valor afetivo e não patrimonial, como o casamento e o divórcio, serão considerados como contratos. Discute-se também se só seriam contratos aqueles celebrados por duas pessoas físicas ou pessoas jurídicas de de direito privado, ou se os acordos celebrados por pessoas jurídicas de direito público - comumente chamados de contratos administrativos - também se encaixariam na categoria.
      
      Contratos que não obedecem as formalidades legais serão reputados como inexistentes ou inválidos, a depender do vício no caso concreto. Sendo inexistentes ou inválidos, serão ineficazes, não produzindo efeitos. O contrato válido e eficaz, por outro lado, é juridicamente exequível, o que signifca que seu descumprimento poderá ser levado ao Poder Judiciário, por meio de uma ação judicial, que poderá resultar na imposição de um fazer ou não fazer a um dos contratantes, ou o pagamento de uma indenização pelo descumprimento contratual.[10]
      
      Em um sentido amplo, um contrato é uma operação econômica entre duas ou mais pessoas.[1][2] Nesse sentido, um contrato é uma troca econômica, visando a circulação de riqueza, sendo sinônimo do conceito de negócio.[3] Sob o ponto de vista do direito, um contrato é a formalização jurídica de uma operação econômica,[4] formalização essa entendida como um instrumento jurídico que vincula os contratantes aos compromissos por eles assumidos.[5] Assim, celebrado um contrato, as partes ficam obrigadas aos seus termos, sob pena de uma sanção legal no caso de descumprimento. Desse modo, pode-se definir um contrato como um acordo de vontades legalmente exequível.[2] A figura jurídica do contrato apresenta-se como uma forma de o legislador regular trocas econômicas e orientá-las segundo critérios políticos.[6] Daí porque cada sistema jurídico apresenta regras distintas sobre contratos, bem como cada sistema econômico também irá apresentar diferentes matizes sobre o direito contratual.[7]
      
      Em uma visão clássica sobre os contratos, influenciada pela ideologia liberal, a figura jurídica do contrato têm como função impor regras de bom funcionamento do mercado, evitando assim que as trocas comerciais sejam inteiramente expostas a acontecimentos imprevisíveis ou ao mero árbitro das partes.[8] A função do direito contratual, portanto, é criar deveres para as partes de modo a limitar seu comportamento, coibindo um conjunto de atitudes prejudiciais ao mercado. Para essa visão, o direito deve se limitar a criar meios para garantir a exequibilidade do contrato, pouco importando o seu conteúdo.[9] Mais recentemente, com o retrocesso do liberalismo clássico, a doutrina passou a discutir outras finalidades contratuais, mais voltadas à coletividade, como a função social do contrato.
      
      O direito vê o contrato como um negócio jurídico, o que significa que esse acordo deve obedecer certos requisitos legais para que se forme, seja considerado válido e produza efeitos. Não há uma uniformidade na matéria, com cada legislação apresentando seus próprios requisitos formais. Há uma forte tendência entre os juristas de considerar como contrato jurídico apenas os acordos de vontade que tenham um conteúdo patrimonial. Há, contudo, aqueles que entendem que todo acordo de vontades protegido pela lei será um contrato, importando dizer que figuras de valor afetivo e não patrimonial, como o casamento e o divórcio, serão considerados como contratos. Discute-se também se só seriam contratos aqueles celebrados por duas pessoas físicas ou pessoas jurídicas de de direito privado, ou se os acordos celebrados por pessoas jurídicas de direito público - comumente chamados de contratos administrativos - também se encaixariam na categoria.
      
      Contratos que não obedecem as formalidades legais serão reputados como inexistentes ou inválidos, a depender do vício no caso concreto. Sendo inexistentes ou inválidos, serão ineficazes, não produzindo efeitos. O contrato válido e eficaz, por outro lado, é juridicamente exequível, o que signifca que seu descumprimento poderá ser levado ao Poder Judiciário, por meio de uma ação judicial, que poderá resultar na imposição de um fazer ou não fazer a um dos contratantes, ou o pagamento de uma indenização pelo descumprimento contratual.[10]
      
    </p>
</div>
</form>